spring:
  datasource:
    url: jdbc:mysql://34.66.20.79:3306/hachimi_db
    username: hachimi
    password: Hachimi4156!
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
info:
  build:
    name: activity-scheduler
    version: 0.0.1-SNAPSHOT
    group: com.example
    artifact: activity-scheduler
    description: Activity Scheduler application

server:
  port: 8080
